[package]
name = "hello_remote_world"
version = "0.1.0"
authors = ["VS Code <vscode@microsoft.com>"]

[lib]
path ="./src/lib/lib.rs"

[dependencies]
clap = { version = "4.5.2", features = ["derive"]}
rand = "0.8.5"
